### ISSUE TITLE
ログの行の最後の１文字が切れる

### ISSUE THREAD

**Issue by plonk** [shinji3/peercast-yt#1]
YT17.2 を試しているうちに気づいたのですが、ログの各行の最後の１文字がつづめられてしまうようです。32bit 版 64bit 版の両方で発生しました。

![image](https://user-images.githubusercontent.com/1680210/27851294-c0c930ac-6194-11e7-86f8-1c7d72580fdd.png)

**Comment by shinji3** [comment]
修正しました。ありがとうございます。
