### ISSUE TITLE
外部サイトからの index.txt の取得に失敗する

### ISSUE THREAD

**Issue by plonk** [shinji3/peercast-yt#2]
YT19 Windows7 で、チャンネルフィードに設定した URL からの index.txt の取得に失敗します。
ログを見ると、64ビット版では `Could not resolve ***` と出るのですが、32 ビット版では `Timeout` と表示されました。

![image](https://user-images.githubusercontent.com/1680210/28261810-bd70c0ec-6b1b-11e7-8961-c0f74b9c2256.png)

![image](https://user-images.githubusercontent.com/1680210/28261812-c1614c80-6b1b-11e7-927e-e14fb5fd5b56.png)

**Comment by shinji3** [comment]
Windows10で試したところ正常に取得出来ました
Windows7でも下の仮想マシンを使って試しましたが正常に取得出来ました
恐らくはファイヤーウォールとかの環境による問題かと思います
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by plonk** [comment]
MinGW 32 ビットで調査してみたのですが（うちの Visual Studio が壊れていてビルドできないのです）、
ホスト名がでたらめな IP アドレスに解決されて、接続がタイムアウトしているようです。

WSAClientSocket::resolveHost で、getaddrinfo で確保される構造体を開放したあと、無効になったポインターを返していませんか？

```
struct in_addr *WSAClientSocket::resolveHost(const char *hostName)
{
    struct in_addr *inAddr;
    struct addrinfo hints, *result;

    memset(&hints, 0, sizeof(hints));
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_family = AF_INET;

    if (getaddrinfo(hostName, NULL, &hints, &result) == 0)
        inAddr = &((struct sockaddr_in *)result->ai_addr)->sin_addr;
    else
        inAddr = NULL;

    freeaddrinfo(result); // ←ここで inAddr の指す先のメモリが開放される

    return inAddr;
}
```

**Comment by shinji3** [comment]
PeerCastYT19.1でコードをこんな感じにして見ましたがどうでしょうか？

	unsigned int WSAClientSocket::resolveHost(const char *hostName)
	{
	    unsigned int ip = NULL;
	    struct addrinfo hints, *res;

	    memset(&hints, 0, sizeof(hints));
	    hints.ai_socktype = SOCK_STREAM;
	    hints.ai_family = AF_INET;

	    if (getaddrinfo(hostName, NULL, &hints, &res) == 0)
	    {
	        struct in_addr inAddr = ((struct sockaddr_in *)res->ai_addr)->sin_addr;
	        ip = ntohl(inAddr.s_addr);
	        freeaddrinfo(res);
	    }

	    return ip;
	}

**Comment by plonk** [comment]
お疲れ様です。YT19.1 で32ビット板64ビット板ともにチャンネルリストが取得できることを確認しました。このイシューを閉じておきますね。
